name: educationgpt
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_generative_ai: ^0.2.0
  file_picker: ^6.1.1
  path: ^1.8.3
  supabase_flutter: ^2.3.4
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.10+1
  shimmer: ^3.0.0
  glassmorphism: ^3.0.0
  animated_gradient: ^0.0.2
  rive: ^0.12.4
  lottie: ^3.0.0
  blur: ^3.1.0
  pdf_render: ^1.4.2
  image: ^4.1.3
  flutter_tesseract_ocr: ^0.4.23
  path_provider: ^2.1.2
  provider: ^6.1.2
  shared_preferences: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/tessdata/
    - assets/tessdata/eng.traineddata
    - assets/tessdata/spa.traineddata
    - assets/tessdata/fra.traineddata