name: educationgpt
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_generative_ai: ^0.2.0
  file_picker: 4.6.1
  path: ^1.8.3
  supabase_flutter: ^2.3.4
  google_fonts: 4.0.4
  flutter_svg: ^2.0.10+1
  shimmer: ^3.0.0
  glassmorphism: ^3.0.0
  animated_gradient: ^0.0.2
  rive: 0.11.4
  lottie: ^3.0.0
  blur: ^3.1.0
  pdf_render: ^1.4.2
  image: ^4.1.3
  flutter_tesseract_ocr: ^0.4.22
  path_provider: ^2.1.1
  provider: ^6.1.2
  shared_preferences: ^2.4.0
  intl: ^0.18.0
  animated_background: ^2.0.0
  animated_text_kit: ^4.2.2

dependency_overrides:
  ffi: ^1.1.2
  http: ^0.13.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/tessdata/
    - assets/tessdata/eng.traineddata
    - assets/tessdata-main/
    - assets/tessdata-main/eng.traineddata
    - assets/tesseract-main/
    - assets/tesseract-main/eng.traineddata
